// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	http1 "net/http"

	http "github.com/go-kit/kit/transport/http"

	endpoint "github.com/emadghaffari/virgool/auth/pkg/endpoint"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	// makeRegisterHandler(m, endpoints, options["Register"])
	// makeLoginUPHandler(m, endpoints, options["LoginUP"])
	// makeLoginPHandler(m, endpoints, options["LoginP"])
	// makeVerifyHandler(m, endpoints, options["Verify"])
	return m
}
