// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package http

import (
	endpoint "github.com/emadghaffari/virgool/blog/pkg/endpoint"
	http "github.com/go-kit/kit/transport/http"
	http1 "net/http"
)

// NewHTTPHandler returns a handler that makes a set of endpoints available on
// predefined paths.
func NewHTTPHandler(endpoints endpoint.Endpoints, options map[string][]http.ServerOption) http1.Handler {
	m := http1.NewServeMux()
	makeCreatePostHandler(m, endpoints, options["CreatePost"])
	makeUpdatePostHandler(m, endpoints, options["UpdatePost"])
	makeGetPostHandler(m, endpoints, options["GetPost"])
	makeDeletePostHandler(m, endpoints, options["DeletePost"])
	makeCreateTagHandler(m, endpoints, options["CreateTag"])
	makeGetTagHandler(m, endpoints, options["GetTag"])
	makeUpdateTagHandler(m, endpoints, options["UpdateTag"])
	makeDeleteTagHandler(m, endpoints, options["DeleteTag"])
	makeUploadHandler(m, endpoints, options["Upload"])
	return m
}
