version: "2"
services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    restart: always
    volumes:
    - .:/go/src/github.com/emadghaffari/virgool
    container_name: auth
    ports:
    - 8800:8081
    - 8801:8082
