version: "2"
services:
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    restart: always
    volumes:
      - ./auth:/go/src/github.com/emadghaffari/virgool
    container_name: auth
    ports:
      - 88800:8081
      - 88801:8082
