filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/mylog/*.log

# you can add more log paths

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"
