// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/emadghaffari/virgool/notification/pkg/endpoint"
	pb "github.com/emadghaffari/virgool/notification/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	sMS    grpc.Handler
	email  grpc.Handler
	verify grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.NotificationServer {
	return &grpcServer{
		email:  makeEmailHandler(endpoints, options["Email"]),
		sMS:    makeSMSHandler(endpoints, options["SMS"]),
		verify: makeVerifyHandler(endpoints, options["Verify"]),
	}
}
