// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/emadghaffari/virgool/blog/pkg/endpoint"
	pb "github.com/emadghaffari/virgool/blog/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createPost grpc.Handler
	updatePost grpc.Handler
	getPost    grpc.Handler
	deletePost grpc.Handler
	createTag  grpc.Handler
	getTag     grpc.Handler
	updateTag  grpc.Handler
	deleteTag  grpc.Handler
	upload     grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.BlogServer {
	return &grpcServer{
		createPost: makeCreatePostHandler(endpoints, options["CreatePost"]),
		createTag:  makeCreateTagHandler(endpoints, options["CreateTag"]),
		deletePost: makeDeletePostHandler(endpoints, options["DeletePost"]),
		deleteTag:  makeDeleteTagHandler(endpoints, options["DeleteTag"]),
		getPost:    makeGetPostHandler(endpoints, options["GetPost"]),
		getTag:     makeGetTagHandler(endpoints, options["GetTag"]),
		updatePost: makeUpdatePostHandler(endpoints, options["UpdatePost"]),
		updateTag:  makeUpdateTagHandler(endpoints, options["UpdateTag"]),
		upload:     makeUploadHandler(endpoints, options["Upload"]),
	}
}
