environment: "development"
# environment: "production"

service:
  name: "auth"
  redis:
    smsDuration: "1s"
    smsCodeVerification: "1s"
    userDuration: "1s"

jaeger:
  hostPort: "jaeger:6831"
  logSpans: true

grpc:
  host: "localhost"
  port: ":8082"
  endpoint: ":8083"

http:
  host: "localhost"
  port: ":8081"
  endpoint: ":8080"

debug:
  host: "localhost"
  port: ":8084"
  endpoint: ":8085"

mysql:
  username: "root"
  password: "password"
  host: "db"
  schema: "virgool_blog"
  driver: "mysql"
  automigrate: true
  logger: true

redis:
  username: ""
  password: ""
  db: 0
  host: "redis:6379"
  logger: ""

vault:
  address: "http://vault:8200"
  token: "s.9JFm7dyhXVIagWhPEUSiYTAN"
  configuration: "virgool/blog"

multiInstanceMode: false

log:
  disableColors: false
  quoteEmptyFields: false

kafka:
  consumer: false
  producer: true
  brokers:
    - "kafka1:9092"
    - "kafka2:9092"
    - "kafka3:9092"
  version: "v1"
  group: ""
  assignor: "range"
  oldest: true
  verbose: false
  topics:
    notif: "notifications"
  username: "admin"
  password: "admin-secret"
  auth: false

jwt:
  secret: "xxxxxxxxxxxxx"
  rSecret: "yyyyyyyyyyyyyyy"

# https://github.com/olivere/elastic/wiki/Client
elk:
  urls:
    - http://elasticsearch:9200
  username: "elastic"
  password: "changeme"
  health_check: "30s"

general:
  upload: "public/upload"
