environment: "development"
# environment: "production"

service:
  name: "notification"
  mincl: 1000
  maxcl: 9999
  redis:
    smsDuration: "5m"
    smsCodeVerification: "10s"
    userDuration: "800m"

jaeger:
  hostPort: "jaeger:6831"
  logSpans: true

grpc:
  host: "localhost"
  port: ":8082"
  endpoint: ":8083"

http:
  host: "localhost"
  port: ":8080"
  endpoint: ":8081"

debug:
  host: "localhost"
  port: ":8084"
  endpoint: ":8085"

redis:
  username: ""
  password: ""
  db: 0
  host: "redis:6379"
  logger: ""

vault:
  address: "http://vault:8200"
  token: "s.9JFm7dyhXVIagWhPEUSiYTAN"
  configuration: "virgool/notification"

multiInstanceMode: false

log:
  disableColors: false
  quoteEmptyFields: false

kafka:
  consumer: true
  producer: false
  brokers:
    - "kafka1:9092"
    - "kafka2:9092"
    - "kafka3:9092"
  version: "v1"
  group: "interval-group"
  assignor: "range"
  oldest: true
  verbose: false
  topics:
    notif: "notifications"
  username: ""
  password: ""
  auth: false

notif:
  sms:
    userApiKey: "a6s5d1a6s5d156as1d56as1d65asd" # CHANGE ME
    secretKey: "6sd4as68d4as8d7498asd1asd1a68s4dasd" # CHANGE ME
    token:
      url: "https://RestfulSms.com/api/Token" # CHANGE ME
      contentType: "application/json" # CHANGE ME
    send:
      templateURL: "https://RestfulSms.com/api/UltraFastSend"
      bodyURL: "https://RestfulSms.com/api/MessageSend"
      lineNumber:
        - "61891891981" # CHANGE ME
      verify:
        templateId: "22108"
        contentType: "application/json"
  email:
    driver: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: 461616816asdsad
    password: 6a5sd16a5sd165sa1da65s1d
    identity: ""
    send:
      template: "notification/template/emailWithBodyTemplate.html"
