// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "github.com/emadghaffari/virgool/auth/pkg/endpoint"
	pb "github.com/emadghaffari/virgool/auth/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	register grpc.Handler
	loginUP  grpc.Handler
	loginP   grpc.Handler
	verify   grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.AuthServer {
	return &grpcServer{
		loginP:   makeLoginPHandler(endpoints, options["LoginP"]),
		loginUP:  makeLoginUPHandler(endpoints, options["LoginUP"]),
		register: makeRegisterHandler(endpoints, options["Register"]),
		verify:   makeVerifyHandler(endpoints, options["Verify"]),
	}
}
